sudo: false
language: go
go:
  - stable
  - master

before_install:
  - go get github.com/golang/lint/golint

script:
  - go install ./...
  - go test -v ./...
  - go vet -x ./...
  - $HOME/gopath/bin/golint -set_exit_status ./...
